### PR TITLE
Add support for Lenovo Tab4 10 (tbx304)

### PR DESCRIPTION
**Pull request by FieryFlames**

### CODE REVIEW

**Comment by FieryFlames** [comment]
@Danct12 can you build with these changes applied and make sure that santoni still works? I don't see any reason it wouldn't but just to be safe

**Comment by Danct12** [comment]
santoni still works after applied this patch.

**Comment by alikates** [comment]
Can you rebase your commits on top of the main branch? The plan is to support all devices on that branch and make the releases from it.

**Comment by FieryFlames** [comment]
Sure, my bad i didn't realize that that branch wasn't the main one

**Comment by alikates** [comment]
It was, the new one was created yesterday. No prob.

**Comment by FieryFlames** [comment]
Done

**Comment by SirSireesh** [comment]
Thanks @FieryFlames, merging!

**Pull request merged**
