### PR TITLE
Add support for Xiaomi Redmi 7 (onclite)

### PR DESCRIPTION
**Pull request by barni2000**
Initial support for Redmi 7, maybe these changes fine for Y3 also.
It needs custom dtbo image https://github.com/barni2000/dtbo-onclite

### CODE REVIEW

**Comment by z3ntu** [comment]
> I have removed all the node what is not need for the boot but the remaining nodes are needed.

This is with erased/empty dtbo partition or not? Curious if the bootloader itself actually uses some of these nodes, on SDM632 Fairphone 3 it doesn't need anything but since the bootloader is buggy a fully empty dtbo image will crash, so this is needed: https://github.com/z3ntu/dtbo-fp3

**Comment by barni2000** [comment]
> > I have removed all the node what is not need for the boot but the remaining nodes are needed.
> 
> This is with erased/empty dtbo partition or not? Curious if the bootloader itself actually uses some of these nodes, on SDM632 Fairphone 3 it doesn't need anything but since the bootloader is buggy a fully empty dtbo image will crash, so this is needed: https://github.com/z3ntu/dtbo-fp3

Thanks this helps

**Review by z3ntu — APPROVED** [review]
Looks sane

**Comment by alikates** [comment]
LGTM

**Pull request merged**
