### PR TITLE
j6primelte: add support for Galaxy J6 Plus

### PR DESCRIPTION
**Pull request by Hinokami-Kagura**
ok~ use minimal dts.

### CODE REVIEW

**Comment by scarface-one** [comment]
Oh hi, didn't notice this, sorry! Does it work properly for you?

**Comment by scarface-one** [comment]
Also this is for msm8917, while this repo is mostly for msm8953. Not sure if its a good idea to merge this here?

**Comment by Hinokami-Kagura** [comment]
Worked, and due to only your repo can work with my device with fastboot support, so I want to improve it....

and because I found some device which is msm8940 or msm8937 already in repo, so if not other concern should be added...

**Comment by scarface-one** [comment]
OK. TBH I don't know much about lk2nd, other than that it is an ugly hack... I will merge this, but you're kinda on your own here. Junak (the person who initially brought up msm8953 with lk2nd and stuff on mainline) is currently taking a break from mainlining...

**Pull request merged**
