### PR TITLE
xiaomi-ysl: Disable pstore

### PR DESCRIPTION
**Pull request by barni2000**
Removed incorrrect lk2nd,pstore property

### CODE REVIEW

**Comment by z3ntu** [comment]
Do you really not want to submit a correction and just delete it? (to be fair,  I have never used this prop so can really only assume what it's supposed to do without checking code)

**Comment by barni2000** [comment]
> Do you really not want to submit a correction and just delete it? (to be fair, I have never used this prop so can really only assume what it's supposed to do without checking code)

This property allows ```oem pstore``` but ramoops was mapped on wrong address in mainline and the right address is overlapping with venus_mem so it cannot be used. I can get results from ramoops but there are some garbage in it so it better to disable for ysl.

**Comment by z3ntu** [comment]
If you add this info into the commit message, then I'm happy.

**Comment by barni2000** [comment]
> If you add this info into the commit message, then I'm happy.

done

**Review by z3ntu — APPROVED** [review]

**Comment by alikates** [comment]
LGTM

**Pull request merged**
