### PR TITLE
Add support for Xiaomi Redmi 7 (xiaomi-onclite)

### PR DESCRIPTION
**Pull request by EralpCelebi**

### CODE REVIEW

**Review by vldly — CHANGES_REQUESTED** [review]
This device tree is 590KB. Note that lk2nd won't use 99.9% of that, also it won't be used for booting the kernel. Please cut it down to only necessary nodes. (for stock bootloader to correctly pick it and boot lk2nd).

**Review by vldly — APPROVED** [review]

**Review by vldly — CHANGES_REQUESTED** [review]
Accidentally approved. Also whole image should fit into 1MiB virtual partition.

**Comment by XRedCubeX** [comment]
@EralpCelebi Where/how did you get such a detailed dts

**Comment by barni2000** [comment]
I think it can be closed. There is another port here https://github.com/msm8953-mainline/lk2nd/pull/53

**Pull request closed without merging**
