### PR TITLE
Add Xiaomi Redmi 5 (Rosy) and Xiaomi Redmi 7 (Onclite) support

### PR DESCRIPTION
**Pull request by hiprivsid**

### CODE REVIEW

**Comment by alikates** [comment]
Hi, can you squash together the changes for each device?

**Comment by hiprivsid** [comment]
> Hi, can you squash together the changes for each device?

How?

**Comment by FlyingThaCat** [comment]
idk why but im always getting this error 
```
[1230] Found an appended flattened device tree (Qualcomm Technologies, Inc. SDM450 + PMI8940 QRD - 338 65547 1 0x0)
[1240] Add DTB entry 338/0001000b/0x00000001/0/10016/20040/0/0/a0ba2f4d/3e0fe
[1240] Device tree exact match the board: <338 65547 0 0x1> == <338 11 1 0x10001>
[1250] Found an appended flattened device tree (Qualcomm Technologies, Inc. SDM450 + PMI8940 QRD - 338 65547 1 0x0)
[1260] Device tree's msm_id doesn't match the board: <338 65547 0 0x1> != <338 11 1 0x10001>
[1270] Delete don't fit DTB entry 338/0001000b/0x00000001/0/10016/20040/0/0/a0ba2f4d/3e0fe
[1280] DTB offset is incorrect, kernel image does not have appended DTB
[1280] Device info 0x00000152/00010001/0x00010008/1, pmic 0x10016/0x20011/0x0/0x0
[1290] dtb not found
```

**Comment by ultra-azu** [comment]
@hiprivsid https://www.sitepoint.com/git-interactive-rebase-guide/

@FlyingThaCat The msm-id doesn't match. Probably needs to be modified.

**Comment by hiprivsid** [comment]
no activity

**Pull request closed without merging**
