### PR TITLE
Daisy touchscreen compatible

### PR DESCRIPTION
**Pull request by ntonnaett**
Mostly copied from https://github.com/msm8916-mainline/lk2nd/pull/217, but for msm8953 and Xiaomi Daisy.

### CODE REVIEW

**Comment by alikates** [comment]
Is this strictly needed? When enabling all touchscreen drivers, all but one will probe so there won't be any issues. I guess this might be a cleaner solution that saves us from having probe error messages on boot.

Also, are we sure that a panel model has always the same touchscreen controller?

**Comment by alikates** [comment]
Btw, don't we need to set the status to 'okay' instead of NOPing the property?

**Comment by apolemus** [comment]
> Is this strictly needed? When enabling all touchscreen drivers, all but one will probe so there won't be any issues. I guess this might be a cleaner solution that saves us from having probe error messages on boot.
> 
> Also, are we sure that a panel model has always the same touchscreen controller?

Enabling all touchscreen drivers in linux won’t work because the probe failing driver will [claim the pins](https://github.com/msm8953-mainline/linux/pull/128#issuecomment-1685363818) the other driver wants to use. ´´IRQF_PROBE_SHARED´´ might introduce latency and had to be added to the touchscreen drivers. So it seems there are two clean solutions.

1. splitting the daisy device tree (like xiaomi-beryllium or pinephone) but then we have to identify hardware revisions or alike somehow.
3. the lk2nd approach.

Sure, we don’t know if the panel touchscreen pairing is always this way but looking at [this](http://deviceinfohw.ru/devices/uploads.php?page=1&platform=qcom&cpu=&brand=Xiaomi&filter=&submit=&Database=&vendor=Xiaomi&model=Mi%20A2%20lite) it very much seems this way.

**Comment by apolemus** [comment]
@ungeskriptet Since you added the otm1911-fhdplus panel and mentioned the use of the gt917d in the postmarketOS mainline channel. Do you have indeed this panel with the Goodix GT917D on your daisy?

**Comment by ungeskriptet** [comment]
@apolemus Yes it has gt917d and otm1911-fhdplus. I don't have daisy though, I helped a friend add support for it.

**Comment by ntonnaett** [comment]
> Btw, don't we need to set the status to 'okay' instead of NOPing the property?

When I created the draft PR, I only copied the source from msm8916. As it works with this change, I assumed NOPing just resets 'status' to the default value. [This](https://billauer.co.il/blog/2017/02/linux-dts-dtsi-status-ok/) confirms my assumptions. NULL and 'okay' both return true.

I think this is ready to be merged.

**Comment by ntonnaett** [comment]
I also just add the touchscreen-compatible properties for the sakura. They seem to have the [same display/touchscreen combinations](http://deviceinfohw.ru/devices/uploads.php?platform=qcom&cpu=CPU&brand=Xiaomi&filter=Redmi+6+Pro&submit=Search).

**Comment by ntonnaett** [comment]
Could we merge this?

**Comment by umeiko** [comment]
mido can be fixed in this way too.

**Pull request merged**
